### ISSUE TITLE
Capital letters 

### ISSUE THREAD

**Issue by IchigoKurosakii** [kmario23/KenLM-training#2]
I am trying to make an arabic language model the problem is the characters are not understandable by many frameworks so I use a simple conversion to map each character to English characters but arabic characters are more than English so there are capital letters in the corpus that will change the meaning if lowered. Will be that an issue to use capital letters?

**Comment by kmario23** [comment]
Hi @IchigoKurosakii 
   Yes, the transliteration is common for languages such as Arabic. Incidentally, I was also working with Arabic language for quite some time and used a sophisticated transliteration and normalization technique to make the model training possible. So, I understand what your problem is about.

As for the lower casing issue, I don't think you need to lowercase it during pre-processing. I just happen to use lowercasing because that is simpler.

So, you can use your fancy pre-processing (transliteration, normalization etc) in `preprocess.py`:

```
for line in sys.stdin:
    for sentence in sentences:
        # your fancy preprocessing steps goes here
        # e.g. transliteration, normalization
        # print(preprocessed_sentence)
```

-----------

Having said that please make sure that your corpus is large enough. Else you might face issues with the model being not powerful enough. [zero probabilities are handled here with the smoothing technique called Kneser-Ney].

Also, since the trained LM was intended to be used with DeepSpeech during decoding, it is expected that DeepSpeech output also spits out the same encoding (transliterated & normalized version of Arabic) as the Language Model data was trained with. Else it won't score it properly (and essentially doesn't make sense to use this LM during decoding anyway!)

**Comment by IchigoKurosakii** [comment]
Thank you very much for your advices.
